name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Version
        run: bun --version

      - name: Install deps
        run: bun install

      - name: Run formatter, linter and import sorting
        run: bun run ci

      - name: Check types
        run: bun run type-check

      - name: Test
        run: bun run test
